import json, re, sys

data = json.load(sys.stdin)
fp = (data.get("tool_input") or {}).get("file_path") or ""
if re.search(r"[\\/]docs[\\/]data[\\/]digest\.json$", fp, re.I):
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": "docs/data/digest.json is generated by scripts/build_digest.py and gitignored -- edit the build script instead, or run it locally to regenerate.",
        }
    }))
else:
    print("{}")
